-- AlterTable
ALTER TABLE `end_user_notifications` MODIFY `type` ENUM('CASE_SUBMITTED', 'CASE_APPROVED', 'CASE_REJECTED', 'FIELD_REJECTED', 'NEW_BOOKING', 'BOOKING_CANCELLED', 'NEW_REVIEW', 'DOCUMENT_EXPIRING', 'ACCOUNT_BLOCKED', 'MASTER_DATA_REQUEST', 'GENERAL') NOT NULL;

-- AlterTable
ALTER TABLE `hotel_admin_notifications` MODIFY `type` ENUM('CASE_SUBMITTED', 'CASE_APPROVED', 'CASE_REJECTED', 'FIELD_REJECTED', 'NEW_BOOKING', 'BOOKING_CANCELLED', 'NEW_REVIEW', 'DOCUMENT_EXPIRING', 'ACCOUNT_BLOCKED', 'MASTER_DATA_REQUEST', 'GENERAL') NOT NULL;

-- AlterTable
ALTER TABLE `master_data_requests` ADD COLUMN `resolution_note` TEXT NULL;

-- AlterTable
ALTER TABLE `system_admin_notifications` MODIFY `type` ENUM('CASE_SUBMITTED', 'CASE_APPROVED', 'CASE_REJECTED', 'FIELD_REJECTED', 'NEW_BOOKING', 'BOOKING_CANCELLED', 'NEW_REVIEW', 'DOCUMENT_EXPIRING', 'ACCOUNT_BLOCKED', 'MASTER_DATA_REQUEST', 'GENERAL') NOT NULL;
