-- AlterTable
ALTER TABLE `case_field_changes` MODIFY `entity_type` ENUM('HOTEL', 'HOTEL_OWNER', 'HOTEL_ADMIN', 'HOTEL_IMAGE', 'HOTEL_DOCUMENT', 'AMENITY', 'POLICY', 'ROOM_TYPE', 'ROOM_TYPE_IMAGE', 'ROOM_FACILITY', 'ROOM_DETAIL') NOT NULL;

-- AlterTable
ALTER TABLE `cases` MODIFY `status` ENUM('DRAFTING', 'PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'DRAFTING';
